
/* ═══════════ painel da dona ═══════════ */
const ATABS = [['checkin', 'Hoje'], ['visao', 'Visão geral'], ['agenda', 'Agenda'], ['alunas', 'Alunas'], ['creditos', 'Créditos'], ['vendas', 'Vendas'], ['pacotes', 'Pacotes'], ['pagamentos', 'Pagamentos'], ['emails', 'E-mails'], ['equipe', 'Equipe'], ['avisos', 'Avisos'], ['estudio', 'Estúdio']];
const METHOD = { INFINITEPAY: 'Pix/cartão (site)', PIX: 'PIX (site)', CASH: 'Dinheiro', CARD_MACHINE: 'Maquininha', PIX_KEY: 'PIX direto', COURTESY: 'Cortesia' };
const ACTIONS = { creditos_ajustados: 'Créditos ajustados', aluna_bloqueada: 'Aluna bloqueada', aluna_desbloqueada: 'Aluna desbloqueada', aula_criada: 'Aula criada', aula_editada: 'Aula editada', aula_cancelada: 'Aula cancelada', grade_gerada: 'Grade gerada', semana_duplicada: 'Semana duplicada', reserva_cancelada: 'Reserva cancelada', pacote_salvo: 'Pacote salvo', venda_manual: 'Venda no estúdio', venda_estornada: 'Venda estornada', pix_confirmado: 'PIX confirmado', configuracoes: 'Configurações salvas', mensalidade: 'Mensalidade', credito_doado: 'Créditos doados', reserva_manual: 'Reserva feita pela Fany' };
const bars = (data, fmt) => { const max = Math.max(1, ...data.map(d => d.v)), step = Math.ceil(data.length / 8); return `<div class="scrollbars"><div class="bars">${data.map((d, i) => `<div class="bar" title="${esc(d.l)}: ${esc(fmt(d.v))}"><i style="height:${Math.round(d.v / max * 100)}%"></i><span>${i % step === 0 ? esc(d.l) : '&nbsp;'}</span></div>`).join('') || '<span class="muted sm">Sem dados ainda</span>'}</div></div>`; };
const students = () => db.users.filter(u => !u.deleted);
const kpi = (k, v, h, act) => `<${act ? 'button data-act="atab" data-t="' + act + '"' : 'div'} class="kpi"><small>${k}</small><b>${v}</b>${h ? `<small>${h}</small>` : ''}</${act ? 'button' : 'div'}>`;

function viewAdmin() {
  const tabs = `<div class="tabs" role="tablist">${ATABS.filter(([id]) => id !== 'equipe' || isOwner()).map(([id, l]) => `<button class="tab ${ui.atab === id ? 'on' : ''}" role="tab" data-act="atab" data-t="${id}">${l}</button>`).join('')}</div>`;
  const fn = { checkin: aCheckin, visao: aOverview, agenda: aAgenda, alunas: aStudents, creditos: aCredits, vendas: aSales, pacotes: aPackages, pagamentos: aPayments, emails: aEmails, equipe: aTeam, avisos: aNews, estudio: aStudio }[ui.atab] || aCheckin;
  return `${topbar()}<main class="wrap" style="padding-top:20px;padding-bottom:90px">${tabs}${fn()}</main>`;
}

function aOverview() {
  const now = new Date(), ms = new Date(now.getFullYear(), now.getMonth(), 1);
  const paid = db.purchases.filter(p => p.status === 'paid');
  const month = paid.filter(p => D(p.paidAt) >= ms);
  const st = students();
  const past = db.classes.filter(c => c.active && D(c.start) < now && D(c.start) > addDays(now, -30));
  const occ30 = past.length ? Math.round(past.reduce((a, c) => a + occ(c.id).length / c.maxBikes, 0) / past.length * 100) : 0;
  const act = new Set(db.reservations.filter(r => ['confirmed', 'attended'].includes(r.status) && cls(r.classId) && D(cls(r.classId).start) < now && D(cls(r.classId).start) > addDays(now, -30)).map(r => r.userId));
  const next = db.classes.filter(c => c.active && D(c.start) > now).sort((a, b) => D(a.start) - D(b.start));
  const rev = {}; for (const p of paid) if (D(p.paidAt) > addDays(now, -30)) { const k = dayKey(p.paidAt); rev[k] = (rev[k] || 0) + p.amount; }
  const revData = Object.keys(rev).sort().map(k => ({ l: k.slice(8) + '/' + k.slice(5, 7), v: rev[k] / 100 }));
  const expiring = st.filter(u => u.credits > 0 && u.expireAt && D(u.expireAt) > now && D(u.expireAt) < addDays(now, 7));
  const lastClass = u => { const rs = db.reservations.filter(r => r.userId === u.id && ['confirmed', 'attended'].includes(r.status) && cls(r.classId) && D(cls(r.classId).start) < now).map(r => D(cls(r.classId).start)); return rs.length ? new Date(Math.max(...rs)) : null; };
  const inactive = st.filter(u => !u.blocked && db.purchases.some(p => p.userId === u.id && p.status === 'paid') && (!lastClass(u) || now - lastClass(u) > 21 * 864e5)).slice(0, 12);
  const people = (rows, msg, hint, empty) => rows.length ? `<div class="stack">${rows.map(u => `<div class="row" style="justify-content:space-between;flex-wrap:nowrap"><div><p>${esc(u.name)}</p><p class="muted xs">${hint(u)}</p></div>${u.phone ? `<a class="btn-line btn-sm" target="_blank" rel="noopener" href="${waLink(u.phone, msg(u))}">WhatsApp</a>` : ''}</div>`).join('')}</div>` : `<p class="muted sm">${empty}</p>`;
  const pending = db.purchases.filter(p => p.status === 'pending' && !p.expired);
  return `<h1 style="font-size:1.9rem;margin-bottom:6px">Painel da Fany</h1><p class="muted" style="margin-bottom:18px">Aulas, alunas, créditos e dinheiro no mesmo lugar.</p>
  ${!server.paymentsReady ? `<button class="card hl sm" style="width:100%;text-align:left;margin-bottom:14px;color:inherit" data-act="atab" data-t="pagamentos"><b class="gold">Falta conectar a InfinitePay.</b> <span class="muted">Sem isso as alunas não conseguem pagar pelo site. Toque aqui para configurar (leva ~5 minutos).</span></button>` : ''}
  ${!server.emailEnabled ? `<button class="card hl sm" style="width:100%;text-align:left;margin-bottom:14px;color:inherit" data-act="atab" data-t="emails"><b class="gold">O envio de e-mails está desligado.</b> <span class="muted">Sem ele não saem confirmação de cadastro, aviso de vaga liberada nem promoções. Toque aqui para ver como ligar.</span></button>` : ''}
  ${!db.classes.some(c => c.active && isFuture(c)) ? `<button class="card hl sm" style="width:100%;text-align:left;margin-bottom:14px;color:inherit" data-act="atab" data-t="agenda"><b class="gold">Sua agenda está vazia.</b> <span class="muted">Crie a grade da semana para as alunas poderem reservar. Toque aqui.</span></button>` : ''}
  <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(190px,1fr))">${kpi('Faturado no mês', brl(month.reduce((a, p) => a + p.amount, 0)), month.length + ' vendas', 'vendas')}${kpi('Faturado total', brl(paid.reduce((a, p) => a + p.amount, 0)), paid.length + ' vendas')}${kpi('Ocupação (30 dias)', occ30 + '%', 'aulas passadas')}${kpi('Alunas ativas (30d)', act.size, st.length + ' cadastradas', 'alunas')}${kpi('Créditos em aberto', st.reduce((a, u) => a + u.credits, 0))}${kpi('Aulas à frente', next.length, '', 'agenda')}${kpi('Pagamentos pendentes', pending.length, pending.filter(p => p.claimed).length + ' já avisaram', 'pix')}${kpi('Lista de espera', db.waitlist.length)}</div>
  <div class="grid g2" style="margin-top:14px"><div class="card"><h2>Ocupação das próximas aulas (%)</h2>${bars(next.slice(0, 12).map(c => ({ l: fTime(c.start), v: Math.round(occ(c.id).length / c.maxBikes * 100) })), v => v + '%')}</div>
  <div class="card"><h2>Receita dos últimos 30 dias (R$)</h2>${bars(revData, v => 'R$ ' + v.toFixed(2).replace('.', ','))}</div></div>
  <div class="grid g2" style="margin-top:14px"><div class="card"><h2>Chame no WhatsApp: créditos vencendo</h2>${people(expiring, u => `Oi ${u.name.split(' ')[0]}! Seus ${u.credits} créditos vencem em ${fDate(u.expireAt)}. Bora reservar uma aula? 🚴`, u => `${u.credits} créditos · vence ${fDate(u.expireAt)}`, 'Ninguém com crédito vencendo nos próximos 7 dias.')}</div>
  <div class="card"><h2>Chame no WhatsApp: sumiram há 3+ semanas</h2>${people(inactive, u => `Oi ${u.name.split(' ')[0]}! Sentimos sua falta no spinning 💛 Tem horário bom essa semana, vamos voltar?`, u => (lastClass(u) ? 'última aula ' + fDate(lastClass(u)) : 'nunca veio') + (u.credits ? ` · ${u.credits} créditos` : ''), 'Todas as alunas que compraram estão ativas. 👏')}</div></div>
  <div class="card" style="margin-top:14px"><h2>Histórico de ações</h2><div class="stack sm" style="max-height:260px;overflow:auto">${db.audit.slice(0, 40).map(a => `<p><span>${esc(ACTIONS[a.action] || a.action)}</span> <span class="muted">· ${esc(fWhen(a.at))}</span>${a.detail ? `<br><span class="muted xs">${esc(a.detail)}</span>` : ''}</p>`).join('') || '<p class="muted">Nada registrado ainda.</p>'}</div></div>`;
}

const BIKE_SVG = '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="17" r="3.4"/><circle cx="18" cy="17" r="3.4"/><path d="M6 17l4-8h5l3 8M10 9l2.5 8M15 9l2-3h2M9 6.5h3"/></svg>';
/** Sala da aula: cada bike mostra o nome da aluna e se ela veio. Toque numa bike para marcar presença, trocar ou reservar. */
function roomCard(c) {
  const rs = occ(c.id), by = new Map(rs.filter(r => r.bike).map(r => [r.bike, r]));
  const nOk = rs.filter(r => r.status === 'attended').length, nNo = rs.filter(r => r.status === 'no_show').length, nWait = rs.length - nOk - nNo;
  const n = c.maxBikes, cols = n <= 8 ? 4 : (window.innerWidth >= 900 ? (n <= 36 ? 6 : 8) : (n <= 20 ? 4 : 6)), L = cols / 2, rows = Math.ceil(n / cols);
  const mv = ui.moving && ui.moving.classId === c.id ? db.reservations.find(r => r.id === ui.moving.resId) : null;
  let cells = '';
  for (let r = 0; r < rows; r++) for (let k = 0; k < cols; k++) {
    if (k === L) cells += '<span></span>';
    const i = r * cols + k + 1; if (i > n) { cells += '<span></span>'; continue; }
    const res = by.get(i), u = res && usr(res.userId);
    const st = !res ? 'free' : isHeld(res) ? 'hold' : res.status === 'attended' ? 'ok' : res.status === 'no_show' ? 'no' : 'res';
    const label = !res ? 'livre' : `${u ? u.name : '?'}, ${st === 'ok' ? 'presente' : st === 'no' ? 'faltou' : st === 'hold' ? 'aguardando PIX' : 'aguardando'}`;
    cells += `<button class="bk adm ${st} ${mv && res && mv.id === res.id ? 'mv' : ''}" data-act="bikeadm" data-c="${c.id}" data-b="${i}" aria-label="Bike ${i}: ${esc(label)}">${st === 'ok' ? '<span class="tick">✔</span>' : st === 'no' ? '<span class="tick">✕</span>' : st === 'hold' ? '<span class="tick">⏳</span>' : ''}${BIKE_SVG}<span>${i}</span><em>${res ? esc(shortName(u ? u.name : '?')) : 'Livre'}</em></button>`;
  }
  const noBike = rs.filter(r => !r.bike);
  const wl = db.waitlist.filter(w => w.classId === c.id).sort((a, b) => D(a.at) - D(b.at));
  const tpl = S().reminder || DEFAULT_REMINDER;
  const when = (dayKey(c.start) === dayKey(new Date()) ? 'hoje' : fDay(c.start).toLowerCase()) + ' às ' + fTime(c.start);
  return `<div class="card" data-room="${c.id}">
  <div class="row" style="justify-content:space-between;align-items:flex-start"><div><h2 style="margin:0">${c.event ? evEmoji(c) + ' ' : ''}${esc(c.title)} · ${fTime(c.start)}</h2><p class="muted sm" style="margin-top:4px">${esc(c.instructor)}${c.event ? ' · aula avulsa ' + brl(c.event.price) : ''} · ${rs.length}/${c.maxBikes} bikes · <span class="ok">${nOk} presente${nOk === 1 ? '' : 's'}</span> · <span class="bad">${nNo} falta${nNo === 1 ? '' : 's'}</span> · <span class="warn">${nWait} aguardando</span></p></div>
    <div class="row" style="gap:6px"><button class="btn-line btn-sm" data-act="addany" data-id="${c.id}" ${rs.length >= c.maxBikes ? 'disabled' : ''}>+ Reservar bike</button><button class="btn btn-sm" data-act="allpresent" data-id="${c.id}" ${nWait ? '' : 'disabled'}>Todas presentes</button></div></div>
  ${mv ? `<div class="card hl sm" style="margin-top:12px">Movendo <b>${esc(shortName((usr(mv.userId) || {}).name))}</b> (bike ${mv.bike || '—'}): toque na nova bike — se estiver ocupada, elas trocam de lugar. <button class="linkbtn" data-act="movecancel">Cancelar</button></div>` : ''}
  <div class="room"><div class="stage">${esc(c.instructor)} · frente da sala</div>
  <div class="map" style="grid-template-columns:repeat(${L},minmax(0,1fr)) 18px repeat(${cols - L},minmax(0,1fr));max-width:${cols * 78 + 18}px">${cells}</div></div>
  <div class="legend"><span><i class="f"></i>Livre</span><span><i class="r"></i>Aguardando</span><span><i class="p"></i>Presente</span><span><i class="a"></i>Faltou</span>${c.event ? '<span><i class="h"></i>Aguardando PIX</span>' : ''}</div>
  ${noBike.length ? `<p class="warn sm" style="margin-top:12px">Sem bike definida: ${noBike.map(r => esc((usr(r.userId) || {}).name || '?')).join(', ')} — toque numa bike livre depois de “Trocar de bike”.</p>` : ''}
  <details style="margin-top:16px"><summary class="sm gold" style="cursor:pointer">Ver lista da turma (${rs.length})</summary><div style="margin-top:10px">${rs.sort((a, b) => (a.bike || 99) - (b.bike || 99)).map(r => { const u = usr(r.userId) || { name: '?' }; return `<div class="row sm" style="justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><span>Bike ${r.bike || '—'} · ${esc(u.name)} <span class="${r.status === 'attended' ? 'ok' : r.status === 'no_show' ? 'bad' : 'muted'}">${isHeld(r) ? '⏳ aguardando PIX' : r.status === 'attended' ? '✔ presente' : r.status === 'no_show' ? '✕ faltou' : ''}</span></span>${u.phone ? `<a class="linkbtn xs" target="_blank" rel="noopener" href="${waLink(u.phone, fill(tpl, { nome: u.name.split(' ')[0], aula: c.title, quando: when, bike: r.bike || '—' }))}">lembrete</a>` : ''}</div>`; }).join('') || '<p class="muted sm">Ninguém reservou ainda.</p>'}</div></details>
  ${wl.length ? `<p class="gold sm" style="margin:16px 0 6px">Lista de espera</p>${wl.map((w, i) => { const u = usr(w.userId) || { name: '?', credits: 0 }; return `<div class="row sm" style="justify-content:space-between"><span>${i + 1}. ${esc(u.name)} · ${u.credits} crédito(s)${u.credits < 1 ? ' <b class="bad">(sem crédito!)</b>' : ''}${w.offerUntil && D(w.offerUntil) > new Date() ? ` · <b class="ok">vaga oferecida até ${fTime(w.offerUntil)}</b>` : ''}</span><button class="linkbtn bad" data-act="wlrm" data-id="${w.id}">tirar</button></div>`; }).join('')}` : ''}</div>`;
}
function aCheckin() {
  const base = addDays(new Date(), ui.hojeOff || 0), dk = dayKey(base), now = new Date();
  const list = db.classes.filter(c => c.active && dayKey(c.start) === dk).sort((a, b) => D(a.start) - D(b.start));
  let sel = list.find(c => c.id === ui.hojeClass);
  if (!sel) { sel = list.find(c => addDays(D(c.start), 0).getTime() + c.duration * 6e4 > now.getTime()) || list[list.length - 1] || null; ui.hojeClass = sel ? sel.id : null; }
  const title = ui.hojeOff ? 'Aulas de ' + fDay(base).toLowerCase() : 'Aulas de hoje';
  return `<div class="row" style="justify-content:space-between;margin-bottom:6px"><h1 style="font-size:1.9rem">${esc(title)}</h1><div class="row" style="gap:6px"><button class="btn-line btn-sm" data-act="hday" data-d="-1" aria-label="Dia anterior">‹</button><button class="btn-line btn-sm" data-act="hday" data-d="0" ${ui.hojeOff ? '' : 'disabled'}>Hoje</button><button class="btn-line btn-sm" data-act="hday" data-d="1" aria-label="Próximo dia">›</button></div></div>
  <p class="muted" style="margin-bottom:14px">${esc(fDay(base))} — toque numa bike para marcar presença ou falta, trocar de lugar ou reservar para alguém.</p>
  <div class="tabs">${list.map(c => `<button class="tab ${sel && sel.id === c.id ? 'on' : ''}" data-act="hclass" data-id="${c.id}">${fTime(c.start)} · ${occ(c.id).length}/${c.maxBikes}</button>`).join('')}</div>
  ${sel ? roomCard(sel) : '<div class="empty">Nenhuma aula nesse dia. Crie na aba Agenda.</div>'}`;
}

function aAgenda() {
  const s = S(), e = ui.editClass ? cls(ui.editClass) : null;
  const f = e || { title: 'Spinning Noturno', instructor: s.instructor, start: '', duration: s.duration, maxBikes: s.maxBikes, level: 'Todos os níveis', notes: '' };
  const list = db.classes.filter(c => c.active && D(c.start) > addDays(new Date(), -1)).sort((a, b) => D(a.start) - D(b.start)).slice(0, 120);
  return `<div class="row" style="justify-content:space-between;margin-bottom:14px"><h1 style="font-size:1.9rem">Agenda</h1><button class="btn-line" data-act="dupweek">Duplicar semana</button></div>
  <div class="grid g2"><form class="card stack" data-form="class"><h2>${e ? 'Editar aula' : 'Nova aula avulsa'}</h2>
    <input class="field" name="title" value="${esc(f.title)}" placeholder="Nome da aula" required><input class="field" name="instructor" value="${esc(f.instructor)}" placeholder="Instrutora">
    <div><label class="lbl">Data e hora</label><input class="field" type="datetime-local" name="start" value="${f.start ? toLocalInput(f.start) : ''}" required></div>
    <div class="row"><div style="flex:1"><label class="lbl">Duração (min)</label><input class="field" type="number" name="duration" min="15" max="180" value="${f.duration}"></div><div style="flex:1"><label class="lbl">Bikes</label><input class="field" type="number" name="maxBikes" min="1" max="80" value="${f.maxBikes}"></div></div>
    <input class="field" name="level" value="${esc(f.level)}" placeholder="Nível"><input class="field" name="notes" value="${esc(f.notes || '')}" placeholder="Aviso para as alunas (opcional)">
    ${f.event ? `<div class="row"><div style="flex:1"><label class="lbl">Preço da aula avulsa (R$)</label><input class="field" name="price" inputmode="decimal" value="${centsToReais(f.event.price)}"></div><div style="flex:1"><label class="lbl">Tema do botão</label><select class="field" name="theme"><option value="havai" ${f.event.theme === 'havai' ? 'selected' : ''}>🌺 Havaí</option><option value="gold" ${f.event.theme !== 'havai' ? 'selected' : ''}>⭐ Dourado</option></select></div></div>` : ''}
    <div class="row"><button class="btn" type="submit" style="flex:1">${e ? 'Salvar alterações' : 'Publicar aula'}</button>${e ? '<button class="btn-line" type="button" data-act="editcancel">Cancelar edição</button>' : ''}</div></form>
  <form class="card stack" data-form="series"><h2>Grade da semana</h2><p class="muted sm">Cria várias aulas de uma vez e não duplica as que já existem.</p>
    <input class="field" name="title" value="Spinning Noturno" required><div class="row">${['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map((d, i) => `<label class="tab" style="display:inline-flex;align-items:center;gap:6px;cursor:pointer"><input type="checkbox" name="d${i}" ${[1, 3, 5].includes(i) ? 'checked' : ''}> ${d}</label>`).join('')}</div>
    <div class="row"><div style="flex:1"><label class="lbl">Hora</label><input class="field" type="number" name="hour" min="0" max="23" value="19"></div><div style="flex:1"><label class="lbl">Minuto</label><input class="field" type="number" name="minute" min="0" max="59" step="5" value="0"></div><div style="flex:1"><label class="lbl">Semanas</label><input class="field" type="number" name="weeks" min="1" max="12" value="2"></div></div>
    <div class="row"><div style="flex:1"><label class="lbl">Duração</label><input class="field" type="number" name="duration" value="${s.duration}"></div><div style="flex:1"><label class="lbl">Bikes</label><input class="field" type="number" name="maxBikes" value="${s.maxBikes}"></div></div>
    <button class="btn" type="submit">Gerar grade</button></form></div>
  ${specialsSection()}
  <h2 class="day">Aulas publicadas</h2>${list.map(c => `<div class="item"><div><p style="font:700 1rem var(--display)">${c.event ? evEmoji(c) + ' ' : ''}${esc(c.title)}${c.event ? ` <span class="pill warn">avulsa ${brl(c.event.price)}</span>` : ''}</p><p class="muted sm cap">${esc(fWhen(c.start))} · ${esc(c.instructor)} · ${c.duration} min · ${occ(c.id).length}/${c.maxBikes}</p></div><div class="row" style="gap:6px"><button class="btn-line btn-sm" data-act="turma" data-id="${c.id}">${ui.openRoster === c.id ? 'Fechar turma' : 'Turma'}</button><button class="btn-line btn-sm" data-act="editclass" data-id="${c.id}">Editar</button><button class="btn-bad btn-sm" data-act="cancelclass" data-id="${c.id}">Cancelar aula</button></div></div>${ui.openRoster === c.id ? roomCard(c) : ''}`).join('') || '<div class="empty">Nenhuma aula publicada.</div>'}`;
}

function specialsSection() {
  const one = t => { const nxt = t.id ? db.classes.filter(c => c.active && c.event && c.event.tpl === t.id && isFuture(c)).sort((a, b) => D(a.start) - D(b.start)) : [];
    return `<div class="card ${t.theme === 'havai' ? 'hw' : ''}" style="padding:0"><form class="stack" data-form="spec" data-id="${t.id}" style="padding:18px"><h2 style="margin-bottom:0">${t.id ? (t.theme === 'havai' ? '🌺 ' : '⭐ ') + esc(t.name) : 'Nova aula especial'}</h2>
    <input class="field" name="name" value="${esc(t.name)}" placeholder="Nome da aula" required>
    <div class="row"><div style="flex:1"><label class="lbl">Preço (R$)</label><input class="field" name="price" inputmode="decimal" value="${centsToReais(t.price)}"></div><div style="flex:1"><label class="lbl">Bikes</label><input class="field" type="number" name="maxBikes" min="1" max="80" value="${t.maxBikes}"></div><div style="flex:1"><label class="lbl">Duração (min)</label><input class="field" type="number" name="duration" min="15" max="240" value="${t.duration}"></div></div>
    <div><label class="lbl">Tema do botão</label><select class="field" name="theme"><option value="havai" ${t.theme === 'havai' ? 'selected' : ''}>🌺 Havaí</option><option value="gold" ${t.theme !== 'havai' ? 'selected' : ''}>⭐ Dourado (padrão)</option></select></div>
    <div><label class="lbl">Descrição (as alunas veem)</label><input class="field" name="desc" value="${esc(t.desc || '')}" maxlength="200"></div>
    <label class="row sm" style="gap:8px"><input type="checkbox" name="active" ${t.active ? 'checked' : ''}> Ativa (pode agendar novas datas)</label>
    ${t.id ? '<label class="row sm" style="gap:8px"><input type="checkbox" name="applyAll" checked> Atualizar também as datas já agendadas</label>' : ''}
    <button class="btn btn-block" type="submit">${t.id ? 'Salvar modelo' : 'Criar aula especial'}</button></form>
    ${t.id ? `<form data-form="specsched" data-id="${t.id}" class="row" style="padding:0 18px 18px"><input class="field" style="flex:1;min-width:190px" type="datetime-local" name="start" required aria-label="Data e hora da nova aula"><button class="btn-ghost" type="submit" ${t.active ? '' : 'disabled'}>+ Agendar data</button></form>
    <p class="muted xs" style="padding:0 18px 16px">${nxt.length ? 'Próximas datas: ' + nxt.map(c => esc(fWhen(c.start))).join(' · ') : 'Nenhuma data agendada.'}</p>` : ''}</div>`; };
  return `<h2 class="day">Aulas especiais (avulsas pagas)</h2><p class="muted sm" style="margin-bottom:12px">Aulas de evento como a Temática Havaí: a aluna paga direto no PIX e já garante a bike — não usa crédito. Edite o preço, o tema e o tamanho aqui; “Agendar data” coloca uma nova aula na agenda.</p>
  <div class="grid g2">${db.specials.map(one).join('')}${one({ id: '', name: 'Nova aula especial', price: 3500, theme: 'gold', maxBikes: 8, duration: 90, desc: '', active: true })}</div>`;
}
function aStudents() {
  return `<div class="row" style="justify-content:space-between;margin-bottom:12px"><h1 style="font-size:1.9rem">Alunas</h1><div class="row"><button class="btn-line btn-sm" data-act="export" data-k="students">Baixar planilha</button><button class="btn btn-sm" data-act="newstud">+ Nova aluna</button></div></div>
  <div class="row" style="margin-bottom:12px"><input class="field" style="max-width:340px" id="sq" placeholder="Buscar nome ou telefone" value="${esc(ui.q)}" data-live="q">${[['todas', 'Todas'], ['creditos', 'Com créditos'], ['semcredito', 'Sem créditos'], ['bloqueadas', 'Bloqueadas']].map(([k, l]) => `<button class="tab ${ui.filter === k ? 'on' : ''}" data-act="sfilter" data-k="${k}">${l}</button>`).join('')}</div>
  <div id="slist">${studentList()}</div>`;
}
function studentList() {
  const q = ui.q.toLowerCase().trim(), qd = digits(ui.q);
  const list = students().filter(u => (!q || u.name.toLowerCase().includes(q) || (qd && (u.phone || '').includes(qd))) && (ui.filter === 'todas' || (ui.filter === 'creditos' && u.credits > 0) || (ui.filter === 'semcredito' && u.credits < 1) || (ui.filter === 'bloqueadas' && u.blocked))).sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
  return `<p class="muted xs" style="margin-bottom:8px">${list.length} resultado(s)</p><div class="scroll-x"><table class="tbl"><thead><tr><th>Nome</th><th>Créditos</th><th>Aulas</th><th>Status</th><th></th></tr></thead><tbody>${list.map(u => { const a = db.reservations.filter(r => r.userId === u.id && r.status === 'attended').length, f = db.reservations.filter(r => r.userId === u.id && r.status === 'no_show').length; return `<tr><td><b>${esc(u.name)}</b><br><span class="muted xs">${u.phone ? esc(fPhone(u.phone)) : 'sem WhatsApp'}${u.email ? ' · ' + esc(u.email) : ''}</span>${u.email && u.emailVerified === false ? ' <span class="pill warn">e-mail não confirmado</span>' : ''}</td><td class="tab-num">${u.credits}</td><td class="muted tab-num">${a}${f ? ` · ${f} falta(s)` : ''}</td><td>${u.blocked ? '<span class="bad">Bloqueada</span>' : 'Ativa'}</td><td><button class="linkbtn" data-act="ostud" data-id="${u.id}">${ui.openStudent === u.id ? 'fechar' : 'abrir'}</button></td></tr>`; }).join('') || '<tr><td colspan="5" class="muted">Nenhuma aluna encontrada.</td></tr>'}</tbody></table></div>${ui.openStudent && usr(ui.openStudent) ? studentEditor(usr(ui.openStudent)) : ''}`;
}
function studentEditor(u) {
  const led = db.ledger.filter(l => l.userId === u.id).sort((a, b) => D(b.at) - D(a.at)).slice(0, 30);
  const spent = db.purchases.filter(p => p.userId === u.id && p.status === 'paid').reduce((a, p) => a + p.amount, 0);
  return `<div class="card hl" style="margin-top:14px"><div class="row sm" style="gap:6px 18px;margin-bottom:10px"><span>✉ ${esc(u.email || 'sem e-mail')} ${u.email ? (u.emailVerified !== false ? '<span class="pill ok">confirmado</span>' : '<span class="pill warn">não confirmado</span>') : ''}</span><span>🪪 CPF: <b id="cpf-${u.id}">${u.cpfMasked || 'não cadastrado'}</b> ${u.hasCpf ? `<button class="linkbtn xs" data-act="revealcpf" data-id="${u.id}">mostrar</button>` : ''}</span><span class="muted xs">${u.mktOptIn ? 'aceita promoções' : 'não aceitou promoções'}</span></div><p class="muted xs" style="margin-bottom:10px">Cadastro: ${fDate(u.createdAt)} · Gastou: ${brl(spent)} · ${u.termsAt ? 'Termo aceito' : 'Termo pendente'}${u.expireAt && u.credits > 0 ? ' · Créditos vencem ' + fDate(u.expireAt) : ''}</p>
  <form data-form="studedit" data-id="${u.id}" class="grid g2"><input class="field" name="name" value="${esc(u.name)}" aria-label="Nome" required><input class="field" name="phone" value="${esc(fPhone(u.phone))}" placeholder="WhatsApp" aria-label="WhatsApp"><input class="field" name="emergency" value="${esc(u.emergency || '')}" placeholder="Contato de emergência" style="grid-column:1/-1"><textarea class="field" name="obs" placeholder="Observações (lesão, preferência de bike…) — só você vê" style="grid-column:1/-1">${esc(u.obs || '')}</textarea>
  <div class="row" style="grid-column:1/-1"><button class="btn btn-sm" type="submit">Salvar</button>${u.hasAccess ? `<button class="btn-line btn-sm" type="button" data-act="resetpw" data-id="${u.id}">Redefinir senha</button>` : `<button class="btn-line btn-sm" type="button" data-act="createaccess" data-id="${u.id}">Criar acesso (e-mail e senha)</button>`}<button class="btn-line btn-sm" type="button" data-act="block" data-id="${u.id}">${u.blocked ? 'Desbloquear' : 'Bloquear'}</button>${u.phone ? `<a class="btn-line btn-sm" target="_blank" rel="noopener" href="${waLink(u.phone)}">WhatsApp</a>` : ''}</div></form>
  <div class="grid g2" style="margin-top:14px"><form data-form="adjust" data-id="${u.id}" class="card stack" style="background:var(--elevated)"><b class="sm">Dar ou tirar créditos</b><div class="row"><input class="field" style="width:90px" type="number" name="amount" value="1" aria-label="Quantidade"><input class="field" style="flex:1;min-width:120px" name="reason" value="Cortesia da Fany"><button class="btn btn-sm" type="submit">Aplicar</button></div><p class="muted xs">Número negativo desconta.</p></form>
  <form data-form="sale" data-id="${u.id}" class="card stack" style="background:var(--elevated)"><b class="sm">Registrar venda no estúdio</b><select class="field" name="pkg">${db.packages.filter(p => p.active).map(p => `<option value="${p.id}">${esc(p.name)} · ${brl(p.price)}</option>`).join('')}</select><div class="row"><select class="field" name="method" style="flex:1"><option value="CASH">Dinheiro</option><option value="CARD_MACHINE">Maquininha</option><option value="PIX_KEY">PIX direto</option><option value="COURTESY">Cortesia (R$ 0)</option></select><button class="btn btn-sm" type="submit">Vender</button></div></form></div>
  <div class="stack xs muted" style="margin-top:12px;max-height:180px;overflow:auto">${led.map(l => `<p class="row" style="justify-content:space-between"><span>${esc(l.desc)} · ${esc(fWhen(l.at))}</span><b style="color:var(--fg)">${l.amount > 0 ? '+' : ''}${l.amount}</b></p>`).join('')}</div></div>`;
}

function creditList() {
  const q = ui.cq.toLowerCase().trim(), qd = digits(ui.cq);
  const list = students().filter(u => !q || u.name.toLowerCase().includes(q) || (qd && (u.phone || '').includes(qd))).sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
  return `<div class="scroll-x"><table class="tbl"><thead><tr><th>Aluna</th><th>Créditos</th><th>Vencem</th><th>Ajuste rápido</th></tr></thead><tbody>${list.map(u => `<tr><td><b>${esc(u.name)}</b><br><span class="muted xs">${u.phone ? esc(fPhone(u.phone)) : 'sem WhatsApp'}</span></td><td class="tab-num"><b class="${u.credits ? 'gold' : 'muted'}">${u.credits}</b></td><td class="muted xs">${u.expireAt && u.credits > 0 ? fDate(u.expireAt) : '—'}</td><td><div class="row" style="gap:6px"><button class="btn-line btn-sm" data-act="qadj" data-id="${u.id}" data-n="-1" ${u.credits < 1 ? 'disabled' : ''} aria-label="Tirar 1 crédito de ${esc(u.name)}">−1</button><button class="btn-line btn-sm" data-act="qadj" data-id="${u.id}" data-n="1" aria-label="Dar 1 crédito para ${esc(u.name)}">+1</button><button class="btn-line btn-sm" data-act="qadj" data-id="${u.id}" data-n="5" aria-label="Dar 5 créditos para ${esc(u.name)}">+5</button></div></td></tr>`).join('') || '<tr><td colspan="4" class="muted">Nenhuma aluna encontrada.</td></tr>'}</tbody></table></div>`;
}
function aCredits() {
  const moves = db.ledger.slice().sort((a, b) => D(b.at) - D(a.at)).slice(0, 30);
  return `<h1 style="font-size:1.9rem">Créditos</h1><p class="muted" style="margin:6px 0 14px">Dê ou tire créditos de qualquer aluna. Tudo fica registrado no extrato dela e no histórico.</p>
  <form class="card" data-form="adjust2" style="margin-bottom:14px"><h2>Ajustar créditos</h2><div class="grid g2"><div><label class="lbl">Aluna</label><select class="field" name="uid" required><option value="">Escolha…</option>${students().slice().sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')).map(u => `<option value="${u.id}">${esc(u.name)} · ${u.credits} crédito(s)</option>`).join('')}</select></div>
  <div class="row" style="align-items:flex-end;flex-wrap:nowrap"><div style="flex:1"><label class="lbl">O que fazer</label><select class="field" name="op"><option value="give">Dar créditos</option><option value="take">Tirar créditos</option></select></div><div style="width:96px"><label class="lbl">Quantos</label><input class="field" type="number" name="qty" min="1" max="200" value="1" required></div></div>
  <div style="grid-column:1/-1"><label class="lbl">Motivo (a aluna vê no extrato)</label><input class="field" name="reason" value="Cortesia da Fany" maxlength="120"></div></div><button class="btn" style="margin-top:14px" type="submit">Aplicar</button></form>
  <div class="row" style="margin-bottom:10px"><input class="field" style="max-width:340px" placeholder="Buscar aluna" value="${esc(ui.cq)}" data-live="cq"><span class="muted sm">Saldo total: <b class="gold">${students().reduce((a, u) => a + u.credits, 0)}</b></span></div>
  <div id="clist">${creditList()}</div>
  <h2 class="day">Últimas movimentações</h2><div class="stack sm">${moves.map(l => { const u = usr(l.userId); return `<p class="row" style="justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:8px"><span>${esc(u ? u.name : '—')} <span class="muted">· ${esc(l.desc)} · ${esc(fWhen(l.at))}</span></span><b class="${l.amount > 0 ? 'ok' : ''}">${l.amount > 0 ? '+' : ''}${l.amount}</b></p>`; }).join('') || '<p class="muted">Sem movimentações.</p>'}</div>`;
}

function aSales() {
  const since = addDays(new Date(), -ui.days);
  const rows = db.purchases.filter(p => D(p.createdAt) >= since).sort((a, b) => D(b.createdAt) - D(a.createdAt));
  const paid = rows.filter(p => p.status === 'paid'), by = {};
  for (const p of paid) by[p.billing] = (by[p.billing] || 0) + p.amount;
  return `<div class="row" style="justify-content:space-between;margin-bottom:12px"><h1 style="font-size:1.9rem">Vendas</h1><div class="row"><select class="field" style="width:auto" data-change="days" aria-label="Período">${[7, 30, 90, 365].map(d => `<option value="${d}" ${ui.days === d ? 'selected' : ''}>${d === 365 ? '1 ano' : d + ' dias'}</option>`).join('')}</select><button class="btn-line btn-sm" data-act="export" data-k="sales">Planilha p/ contador</button></div></div>
  <div class="grid g4">${kpi('Total no período', brl(paid.reduce((a, p) => a + p.amount, 0)), paid.length + ' vendas pagas')}${Object.entries(by).map(([m, v]) => kpi(METHOD[m] || m, brl(v))).join('')}</div>
  <form data-form="quicksale" class="card row" style="margin:14px 0"><b class="sm" style="width:100%">Nova venda no balcão</b><select class="field" name="uid" style="flex:1;min-width:170px" required><option value="">Aluna…</option>${students().map(u => `<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select><select class="field" name="pkg" style="flex:1;min-width:170px">${db.packages.filter(p => p.active).map(p => `<option value="${p.id}">${esc(p.name)} · ${brl(p.price)}</option>`).join('')}</select><select class="field" name="method" style="width:auto"><option value="CASH">Dinheiro</option><option value="CARD_MACHINE">Maquininha</option><option value="PIX_KEY">PIX direto</option><option value="COURTESY">Cortesia</option></select><button class="btn" type="submit">Vender</button></form>
  <div class="scroll-x"><table class="tbl"><thead><tr><th>Data</th><th>Aluna</th><th>Pacote</th><th>Valor</th><th>Forma</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(p => { const u = usr(p.userId); return `<tr><td>${esc(fWhen(p.createdAt))}</td><td>${esc(u ? u.name : '—')}</td><td>${esc(purName(p))}${p.kind === 'event' ? ' <span class="pill">avulsa</span>' : ''}</td><td>${brl(p.amount)}</td><td>${esc(METHOD[p.billing] || p.billing)}</td><td>${p.status === 'paid' ? '<span class="ok">Pago</span>' : p.status === 'refunded' ? '<span class="bad">Estornado</span>' : p.status === 'cancelled' ? 'Cancelado' : p.expired ? 'Expirado' : 'Aguardando'}</td><td>${p.status === 'paid' && p.amount > 0 ? `<button class="linkbtn bad xs" data-act="refund" data-id="${p.id}">estornar</button>` : ''}</td></tr>`; }).join('') || '<tr><td colspan="7" class="muted">Nenhuma venda nesse período.</td></tr>'}</tbody></table></div>`;
}

function aPackages() {
  const one = p => `<form class="card stack" data-form="pkg" data-id="${p.id}"><input class="field" name="name" value="${esc(p.name)}" aria-label="Nome" required>
  <div class="row"><div style="flex:1"><label class="lbl">Créditos</label><input class="field" type="number" name="credits" min="1" value="${p.credits}"></div><div style="flex:1"><label class="lbl">Preço (R$)</label><input class="field" name="price" inputmode="decimal" value="${centsToReais(p.price)}"></div></div>
  <input class="field" name="desc" value="${esc(p.desc || '')}" placeholder="Descrição curta"><div><label class="lbl">Validade dos créditos (dias — vazio = não vence)</label><input class="field" type="number" name="validity" min="1" value="${p.validity || ''}"></div>
  <select class="field" name="kind"><option value="credits" ${p.kind === 'credits' ? 'selected' : ''}>Pacote de créditos (pagamento único)</option><option value="subscription" ${p.kind === 'subscription' ? 'selected' : ''}>Mensalidade (renova todo mês)</option></select>
  <div class="row"><div style="flex:1"><label class="lbl">Ordem no site (menor aparece primeiro)</label><input class="field" type="number" name="sort" min="0" value="${p.sort ?? 99}"></div></div>
  <label class="row sm" style="gap:8px"><input type="checkbox" name="highlight" ${p.highlight ? 'checked' : ''}> Destacar este plano (borda dourada)</label>
  <label class="row sm" style="gap:8px"><input type="checkbox" name="active" ${p.active ? 'checked' : ''}> Ativo no site</label><div class="row"><button class="btn" style="flex:1" type="submit">${p.id ? 'Salvar' : 'Criar pacote'}</button>${p.id ? `<button class="btn-bad" type="button" data-act="pkgdel" data-id="${p.id}">Apagar</button>` : ''}</div></form>`;
  return `<h1 style="font-size:1.9rem">Pacotes</h1><p class="muted" style="margin:6px 0 16px">Edite nome, preço, créditos, validade, ordem e destaque. Mudanças valem para compras futuras. Para esconder do site, desmarque “Ativo”; só dá para apagar um plano que nunca foi vendido.</p><div class="grid g2">${db.packages.slice().sort((a, b) => a.sort - b.sort).map(one).join('')}${one({ id: '', name: 'Novo pacote', credits: 5, price: 19900, desc: '', kind: 'credits', validity: null, active: true, sort: db.packages.length + 1, highlight: false })}</div>`;
}

function aPayments() {
  const pend = db.purchases.filter(p => p.status === 'pending').sort((a, b) => D(b.createdAt) - D(a.createdAt)).slice(0, 60);
  const subs = db.subs.slice().sort((a, b) => D(b.createdAt) - D(a.createdAt));
  const base = server.publicUrl || location.origin;
  return `<h1 style="font-size:1.9rem">Pagamentos</h1>
  <div class="card ${server.paymentsReady ? '' : 'hl'}" style="margin:14px 0"><h2>Checkout InfinitePay ${server.paymentsReady ? '<span class="pill ok">conectado</span>' : '<span class="pill warn">falta conectar</span>'}</h2>
    <p class="muted sm">As alunas pagam com <b>Pix</b> ou <b>cartão</b> no checkout seguro da InfinitePay e os créditos caem sozinhos. Pix: sem taxa. Cartão: taxa da InfinitePay (veja no seu app).</p>
    <ol class="muted sm" style="margin:12px 0;padding-left:20px;line-height:1.7"><li>No app InfinitePay: <b>Vendas › Checkout › Configurações › Habilitar Checkout Integrado</b>.</li><li>Copie sua <b>InfiniteTag</b> (aparece no canto superior do app, sem o $) e cole abaixo.</li><li>Toque em <b>Testar conexão</b>. Não precisa configurar webhook: o sistema envia o endereço em cada cobrança.</li></ol>
    ${isOwner() ? `<form data-form="payhandle" class="row" style="align-items:flex-end"><div style="flex:1;min-width:200px"><label class="lbl">InfiniteTag (sem o $)</label><input class="field" name="handle" value="${esc(S().infinitepayHandle || '')}" placeholder="minha_tag" ${server.handleFromEnv ? 'disabled' : ''} autocomplete="off"></div><button class="btn" type="submit" ${server.handleFromEnv ? 'disabled' : ''}>Salvar</button><button class="btn-ghost" type="button" data-act="testcheckout" ${server.paymentsReady ? '' : 'disabled'}>Testar conexão</button></form>
    ${server.handleFromEnv ? '<p class="muted xs" style="margin-top:8px">A InfiniteTag está definida nas variáveis do servidor.</p>' : ''}` : '<p class="muted sm">Só a dona altera a conta de pagamento.</p>'}
    <p class="muted xs" style="margin-top:10px">Endereço do site: ${esc(base)}</p></div>
  <form class="card row" data-form="charge" style="margin-bottom:14px"><b class="sm" style="width:100%">Cobrar uma aluna por link</b><select class="field" name="uid" required style="flex:1;min-width:170px"><option value="">Aluna…</option>${students().slice().sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')).map(u => `<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select><select class="field" name="pkg" style="flex:1;min-width:170px">${db.packages.filter(p => p.active).map(p => `<option value="${p.id}">${esc(p.name)} · ${brl(p.price)}</option>`).join('')}</select><button class="btn" type="submit" ${server.paymentsReady ? '' : 'disabled'}>Gerar link</button></form>
  <h2 class="day" style="margin-top:6px">Pedidos aguardando pagamento</h2><p class="muted sm" style="margin-bottom:8px">Quando a aluna paga, o pedido some daqui sozinho. Se alguém pagou e o crédito não caiu, confira no app da InfinitePay e use “Já recebi”.</p>
  ${pend.map(p => { const u = usr(p.userId), ev = p.kind === 'event'; const rr = ev && db.reservations.find(x => x.pay === p.id && x.status === 'confirmed'); return `<div class="item"><div><p>${esc(u ? u.name : '—')} · ${ev ? evEmoji(cls(p.classId)) + ' ' : ''}${esc(purName(p))} ${p.needsAction ? '<span class="pill bad">pago, mas sem vaga — devolver</span>' : ''}${p.expired ? '<span class="pill warn">reserva expirou</span>' : ''}</p><p class="muted sm">${brl(p.amount)} · ${ev ? 'aula avulsa · bike ' + ((rr && rr.bike) || p.bike || '—') : p.credits + ' créditos'} · ${esc(fWhen(p.createdAt))}</p>${p.note && p.needsAction ? `<p class="bad xs">${esc(p.note)}</p>` : ''}</div><div class="row" style="gap:6px">${p.checkoutUrl && u && u.phone ? `<a class="btn-line btn-sm" target="_blank" rel="noopener" href="${waLink(u.phone, `Oi ${u.name.split(' ')[0]}! Aqui está o link para finalizar seu pagamento no Spinning Fany: ${p.checkoutUrl}`)}">Enviar link</a>` : ''}<button class="btn btn-sm" data-act="markpaid" data-id="${p.id}">Já recebi · liberar</button><button class="btn-line btn-sm" data-act="dropbuy" data-id="${p.id}">Descartar</button></div></div>`; }).join('') || '<div class="empty">Nenhum pedido aguardando.</div>'}
  <h2 class="day">Mensalidades</h2><p class="muted sm" style="margin-bottom:8px">A mensalidade renova por link: todo mês toque em “Enviar link do mês” e mande para a aluna pelo WhatsApp. Pagou, os 20 créditos caem sozinhos.</p>
  ${subs.map(m => { const u = usr(m.userId), k = pkg(m.pkgId); return `<div class="item"><div><p>${esc(u ? u.name : '—')} · ${esc(k ? k.name : '')}</p><p class="muted sm">${m.status === 'active' ? 'ativa' : 'encerrada'} · ${m.credits} créditos/mês · último link ${fDate(m.lastCharge)}</p></div><div class="row" style="gap:6px">${m.status === 'active' ? `<button class="btn btn-sm" data-act="chargesub" data-id="${m.id}" ${server.paymentsReady ? '' : 'disabled'}>Enviar link do mês</button><button class="btn-bad btn-sm" data-act="subend" data-id="${m.id}">Encerrar</button>` : ''}</div></div>`; }).join('') || '<div class="empty">Nenhuma mensalidade ainda.</div>'}`;
}

const AUD = [['all', 'Todas as alunas que aceitam novidades'], ['withCredits', 'Quem tem créditos'], ['noCredits', 'Quem está sem créditos (lembrar de comprar)'], ['inactive', 'Quem não vem há 3 semanas'], ['expiring', 'Quem tem crédito vencendo em 7 dias']];
function aEmails() {
  const m = server.mail || {}, camps = db.campaigns || [];
  const status = m.enabled
    ? `<p class="muted sm" style="margin:6px 0 16px">Enviando por <b>${esc(m.provider)}</b> como <b>${esc(m.from)}</b>. Hoje: <b>${m.sentToday}</b> de ${m.limit} enviados · ${m.pending} na fila${m.failed ? ` · <span class="bad">${m.failed} com erro</span>` : ''}.</p>`
    : `<div class="card hl" style="margin:12px 0"><h2>Ligar o envio de e-mails</h2><p class="muted sm">Hoje o site <b>não envia e-mails</b>. Ligando, saem: confirmação de cadastro, “esqueci a senha”, aviso de vaga liberada na fila (para confirmar), avisos de crédito e as promoções.</p><ol class="muted sm" style="margin:10px 0 0;padding-left:20px;line-height:1.7"><li>Crie uma conta grátis na <b>Brevo</b> (300 e-mails por dia) e gere uma <b>chave de API</b>.</li><li>No Railway, crie as variáveis <b>BREVO_API_KEY</b> (a chave) e <b>EMAIL_FROM</b> (ex.: <i>Spinning Fany &lt;avisos@seudominio.com.br&gt;</i>).</li><li>Reinicie. Esta tela vai mostrar “Enviando por brevo”. Passo a passo completo no guia.</li></ol></div>`;
  return `<h1 style="font-size:1.9rem">E-mails</h1>${status}
  <form data-form="campaign" class="card stack" style="max-width:640px;margin-bottom:18px"><h2>Nova mensagem promocional</h2>
  <div><label class="lbl">Para quem</label><select class="field" name="audience">${AUD.map(([v, l]) => `<option value="${v}">${l}</option>`).join('')}</select></div>
  <div class="row"><button class="btn-line btn-sm" type="button" data-act="campcount">Ver quantas vão receber</button><span id="campcount" class="muted sm"></span></div>
  <div><label class="lbl">Assunto</label><input class="field" name="subject" maxlength="120" placeholder="Ex.: Sábado tem Aula Temática Havai 🌺" required></div>
  <div><label class="lbl">Mensagem (use {nome} para o nome da aluna)</label><textarea class="field" name="body" rows="6" maxlength="3000" placeholder="Oi {nome}!&#10;Sábado às 17h tem Aula Temática Havai. Garanta sua bike!" required></textarea></div>
  <div class="row"><div style="flex:1;min-width:150px"><label class="lbl">Texto do botão (opcional)</label><input class="field" name="buttonLabel" maxlength="40" placeholder="Garantir minha vaga"></div><div style="flex:1;min-width:150px"><label class="lbl">Link do botão (opcional)</label><input class="field" name="buttonUrl" maxlength="300" placeholder="/#/conta"></div></div>
  <div class="row"><button class="btn-line" type="button" data-act="camptest" ${m.enabled ? '' : 'disabled'}>Enviar teste para mim</button><button class="btn" type="submit" ${m.enabled ? '' : 'disabled'}>Enviar para as alunas</button></div>
  <p class="muted xs">Só recebe quem <b>confirmou o e-mail</b> e <b>aceitou novidades</b>. Todo e-mail tem link para descadastrar. Promoções não saem de madrugada (21h às 8h). Se passar do limite diário do plano grátis, o resto sai no dia seguinte.</p></form>
  <h2 class="day" style="margin-top:6px">Mensagens enviadas</h2>
  ${camps.map(c => `<div class="item"><div><p style="font:700 1rem var(--display)">${esc(c.subject)}</p><p class="muted sm">${esc(fWhen(c.createdAt))} · ${esc(c.createdBy || '')} · ${esc((AUD.find(a => a[0] === c.audience) || [0, c.audience])[1])}</p></div><div class="sm" style="text-align:right"><b class="ok">${c.sent}</b> enviados de ${c.total}${c.failed ? `<br><span class="bad">${c.failed} com erro</span>` : ''}</div></div>`).join('') || '<div class="empty">Nenhuma campanha ainda.</div>'}`;
}

function aTeam() {
  if (!isOwner()) return '<div class="empty">Só a dona acessa a equipe.</div>';
  const team = db.users.filter(u => u.role === 'owner' || u.role === 'admin');
  return `<h1 style="font-size:1.9rem">Equipe</h1><p class="muted" style="margin:6px 0 14px">Administradoras entram no painel e cuidam das aulas, alunas e vendas. Só você (dona) cria administradoras, muda a conta de pagamento e baixa a cópia de segurança. Quem cria conta pelo site entra como aluna.</p>
  <form class="card stack" data-form="teamadd" style="max-width:520px;margin-bottom:16px"><h2>Adicionar administradora</h2><input class="field" name="name" placeholder="Nome" required maxlength="120"><input class="field" type="email" name="email" placeholder="E-mail" required autocomplete="off"><input class="field" name="password" placeholder="Senha temporária (mínimo 8 caracteres)" minlength="8" required autocomplete="off"><p class="muted xs">Se esse e-mail já tem conta de aluna, ela vira administradora e continua com a senha dela (o campo senha é ignorado).</p><button class="btn" type="submit">Adicionar</button></form>
  ${team.map(u => `<div class="item"><div><p><b>${esc(u.name)}</b> <span class="pill ${u.role === 'owner' ? 'ok' : 'warn'}">${u.role === 'owner' ? 'dona' : 'administradora'}</span></p><p class="muted sm">${esc(u.email)}</p></div><div class="row" style="gap:6px">${u.role === 'admin' ? `<button class="btn-line btn-sm" data-act="resetpw" data-id="${u.id}">Redefinir senha</button><button class="btn-bad btn-sm" data-act="teamremove" data-id="${u.id}">Remover acesso</button>` : ''}</div></div>`).join('')}`;
}

function aNews() {
  return `<h1 style="font-size:1.9rem">Avisos do mural</h1><p class="muted" style="margin:6px 0 14px">Aparece na página inicial. O mais recente fica em destaque.</p>
  <form class="card stack" data-form="ann"><input class="field" name="title" placeholder="Título" maxlength="80" required><textarea class="field" name="body" placeholder="Mensagem para as alunas" maxlength="400" required></textarea><button class="btn" type="submit">Publicar</button></form>
  <div style="margin-top:12px">${db.announcements.map(a => `<div class="item"><div><p style="font:700 1rem var(--display)">${esc(a.title)}</p><p class="muted sm">${esc(a.body)}</p></div><button class="linkbtn bad" data-act="anndel" data-id="${a.id}">apagar</button></div>`).join('')}</div>`;
}

function aStudio() {
  const s = S(); const f = (k, l, ph = '') => `<div><label class="lbl">${l}</label><input class="field" name="${k}" value="${esc(s[k])}" placeholder="${ph}"></div>`;
  return `<h1 style="font-size:1.9rem;margin-bottom:12px">Estúdio</h1>
  <div class="card hl" style="max-width:560px;margin-bottom:16px"><h2>Aulas especiais e planos</h2><p class="muted sm" style="margin-bottom:12px">Edite o preço, o tema e as datas da Aula Temática Havai, e os planos de crédito (preço, créditos, validade, destaque).</p><div class="row"><button class="btn btn-sm" data-act="atab" data-t="agenda">🌺 Aulas especiais</button><button class="btn-line btn-sm" data-act="atab" data-t="pacotes">Planos e pacotes</button></div></div>
  <form class="stack" data-form="studio" style="max-width:560px">${f('name', 'Nome')}${f('address', 'Endereço')}${f('whatsapp', 'WhatsApp do estúdio (com DDD)', '18 99667-6637')}${f('instructor', 'Instrutora padrão')}${f('instagram', 'Instagram', '@spinningfany')}
  <div><label class="lbl">Sobre</label><textarea class="field" name="about">${esc(s.about)}</textarea></div>
  <div class="row"><div style="flex:1"><label class="lbl">Bikes</label><input class="field" type="number" name="maxBikes" min="1" value="${s.maxBikes}"></div><div style="flex:1"><label class="lbl">Duração</label><input class="field" type="number" name="duration" min="15" value="${s.duration}"></div><div style="flex:1"><label class="lbl">Cancelar até (h)</label><input class="field" type="number" name="cancelHours" min="0" value="${s.cancelHours}"></div></div>
  <div><label class="lbl">Termo de responsabilidade</label><textarea class="field" name="terms" rows="4">${esc(s.terms)}</textarea></div>
  <div><label class="lbl">Mensagem de lembrete no WhatsApp (use {nome} {aula} {quando} {bike})</label><textarea class="field" name="reminder">${esc(s.reminder)}</textarea></div>
  <label class="row sm" style="gap:8px"><input type="checkbox" name="gifts" ${s.gifts === false ? '' : 'checked'}> Permitir que as alunas doem créditos umas para as outras</label>
  <button class="btn" type="submit">Salvar estúdio</button></form>
  ${isOwner() ? `<div class="card stack" style="margin-top:22px;max-width:560px"><h2>Cópia de segurança</h2><p class="muted sm">O sistema guarda uma cópia automática por dia no servidor. Baixe uma cópia sua de vez em quando e guarde em lugar seguro (contém dados das alunas).</p><div class="row"><a class="btn-line btn-sm" href="/api/backup" download>Baixar cópia (.json)</a><button class="btn-line btn-sm" data-act="export" data-k="classes">Relatório de aulas</button></div></div>` : `<div class="row" style="margin-top:22px"><button class="btn-line btn-sm" data-act="export" data-k="classes">Relatório de aulas</button></div>`}`;
}
